# Generated by Django 2.2.12 on 2020-06-11 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('\\+(\\d+)')]),
        ),
    ]
