# Generated by Django 2.2.12 on 2020-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200611_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_end', models.DateTimeField(blank=True, null=True)),
                ('employer', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='text',
            new_name='description',
        ),
    ]
