# Generated by Django 2.2.12 on 2020-06-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200611_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='start_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_end',
            new_name='end_date',
        ),
    ]
