# Generated by Django 2.2.12 on 2020-06-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200612_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=16)),
                ('last', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
