# Generated by Django 2.2.12 on 2020-06-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200620_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
