# Generated by Django 2.2.12 on 2020-06-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20200620_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
